version: "3.7" # https://docs.docker.com/compose/compose-file/

volumes:
    prometheus-config:
        labels:
            com.example.prometheus-config.description: "Prometheus config"
            com.example.prometheus-config.department: "DevOps"
    prometheus-data:
        labels:
            com.example.prometheus-data.description: "Prometheus data"
            com.example.prometheus-data.department: "DevOps"
    grafana-config:
        labels:
            com.example.grafana-config.description: "Grafana config"
            com.example.grafana-config.department: "DevOps"
    grafana-data:
        labels:
            com.example.grafana-data.description: "Grafana data"
            com.example.grafana-data.department: "DevOps"

services:
    prometheus:
        image: "prom/prometheus:v2.4.3"
        network_mode: "host"
        volumes:
            - "prometheus-config:/etc/prometheus"
            - "prometheus-data:/prometheus"
        #environment:
        #    - TZ=Asia/Shanghai
        command:
            - --web.listen-address=0.0.0.0:9090
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
        restart: always
    grafana:
        image: "grafana/grafana:5.3.2"
        network_mode: "host"
        volumes:
            - "grafana-config:/etc/grafana"
            - "grafana-data:/var/lib/grafana"
        restart: always
