version: "3.7" # https://docs.docker.com/compose/compose-file/

volumes:
    prometheus-config:
        labels:
            com.example.prometheus-config.description: "Prometheus config"
            com.example.prometheus-config.department: "DevOps"
    prometheus-data:
        labels:
            com.example.prometheus-data.description: "Prometheus data"
            com.example.prometheus-data.department: "DevOps"
    grafana-config:
        labels:
            com.example.grafana-config.description: "Grafana config"
            com.example.grafana-config.department: "DevOps"
    grafana-data:
        labels:
            com.example.grafana-data.description: "Grafana data"
            com.example.grafana-data.department: "DevOps"
    #alertmanager-config:
    #    labels:
    #        com.example.alertmanager-config.description: "Alertmanager config"
    #        com.example.alertmanager-config.department: "DevOps"
    filebeat-data:
        labels:
            com.example.filebeat-data.description: "Filebeat data"
            com.example.filebeat-data.department: "DevOps"
    elasticsearch-data:
        labels:
            com.example.elasticsearch-data.description: "Elasticsearch data"
            com.example.elasticsearch-data.department: "DevOps"

services:
    prometheus:
        image: "prom/prometheus:v2.4.3"
        network_mode: "host"
        volumes:
            - "prometheus-config:/etc/prometheus"
            - "prometheus-data:/prometheus"
        #environment:
        #    - TZ=Asia/Shanghai
        command:
            - --web.listen-address=0.0.0.0:9090
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
        restart: always
        #logging:
        #    driver: "syslog"
        #    options:
        #        syslog-address: "udp://127.0.0.1:9000"
        #        tag: "app-prometheus"
    grafana:
        image: "grafana/grafana:5.3.2"
        network_mode: "host"
        volumes:
            - "grafana-config:/etc/grafana"
            - "grafana-data:/var/lib/grafana"
        restart: always
    #alertmanager:
    #    image: "prom/alertmanager:v0.15.2"
    #    network_mode: "host"
    #    volumes:
    #        - "alertmanager-config:/etc/alertmanager"
    #    restart: always
    filebeat:
        image: "docker.elastic.co/beats/filebeat-oss:6.4.2"
        network_mode: "host"
        volumes:
            - "filebeat-data:/usr/share/filebeat/data:rw"
            #- "/var/lib/docker/containers:/usr/share/filebeat/dockerlogs:ro"
            #- "/var/run/docker.sock:/var/run/docker.sock:ro"
        restart: always
        build:
            context: ./filebeat
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2"
        network_mode: "host"
        volumes:
            - "elasticsearch-data:/usr/share/elasticsearch/data"
        restart: always
