version: "2.1" # https://docs.docker.com/compose/compose-file/#version-21
volumes:
    data-drupal8-src:
        labels:
            com.example.web1.description: "Drupal 8 source code"
            com.example.web1.department: "DevOps"
    data-db:
        labels:
            com.example.web1.description: "MySQL database"
            com.example.web1.department: "DevOps"
networks:
    front:
        #driver: "bridge"
        #ipam:
        #    config:
        #        - subnet: "172.25.0.0/24"
    back:
services:
    db1:
        #hostname: "db1.local"
        image: "junhsieh/docker-mysqld"
        volumes:
            - "data-db:/var/lib/mysql"
        networks:
            - "back"
        environment:
            - MYSQL_ROOT_PASSWORD=foo
    dru1:
        #hostname: "php1.local"
        image: "junhsieh/docker-php-fpm"
        volumes:
            - "data-drupal8-src:/var/www/html"
        networks:
            - "front"
            - "back"
            ##front:
            ##    aliases:
            ##        - "myappip"
            ##back:
        #expose:
        #    - "9000"
    web1:
        #hostname: "web1.local"
        image: "junhsieh/docker-httpd"
        volumes:
            - "data-drupal8-src:/usr/local/apache2/htdocs/drupal8"
        networks:
            - "front"
        ports:
            - "80:80"
        #expose:
        #    - "80"
