version: "3.7" # https://docs.docker.com/compose/compose-file/

networks:
    back:
        driver: bridge
        ipam:
            config:
                - subnet: 169.254.5.16/28

services:
    qpid-cpp-broker:
        build:
            context: .
            #network: host
            dockerfile: image/qpid-cpp-broker/Dockerfile
            args:
                CENTOS_TAG: ${CENTOS_TAG}
        image: ${COMPOSE_PROJECT_NAME}/${CENTOS_TAG}
        networks:
            - back
        ports:
            - "5672:5672"
        tty: true