version: "3.7" # https://docs.docker.com/compose/compose-file/

volumes:
    registry-data:
        labels:
            com.example.registry-data.description: "ES data"
            com.example.registry-data.department: "DevOps"
    es-data:
        labels:
            com.example.es-data.description: "ES data"
            com.example.es-data.department: "DevOps"
    web-data:
        labels:
            com.example.web-data.description: "Web data"
            com.example.web-data.department: "DevOps"

#networks:
#    front:
#        driver: "bridge"
#        ipam:
#            config:
#                - subnet: "192.168.5.8/29"
#    back:

services:
    registry:
        image: "registry:2.6.2"
        network_mode: "host"
        volumes:
            - "registry-data:/var/lib/registry"
        environment:
            REGISTRY_HTTP_SECRET: "your-http-secret"
            #REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/LETSENCRYPT_DOMAINS_ENV_VAR/fullchain.pem
            #REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/LETSENCRYPT_DOMAINS_ENV_VAR/privkey.pem
        restart: "always"
    main:
        image: "exp/main:0.0.0"
        network_mode: "host"
        volumes:
            - "/QA_files:/QA_files:rw"
            - "web-data:/web_static"
        environment:
            TZ: Asia/Shanghai
        #logging:
        ##    driver: "syslog"
        #    options:
        ##        syslog-address: "udp://127.0.0.1:514"
        #        tag: "app-main"
    nginx:
        image: "nginx:1.15"
        network_mode: "host"
        #networks:
        #    - "front"
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:514"
                tag: "app-nginx"
                #syslog-format: "rfc3164"
                #syslog-facility: "daemon"
                #https://docs.docker.com/config/containers/logging/syslog/#options
    rsyslog:
        image: "voxxit/rsyslog"
        network_mode: "host"
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:514"
                tag: "app-rsyslog"
    filebeat:
        image: "docker.elastic.co/beats/filebeat-oss:6.4.2"
        network_mode: "host"
    es:
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2"
        network_mode: "host"
        volumes:
            - "es-data:/usr/share/elasticsearch/data"
    #kibana:
    #    image: "docker.elastic.co/kibana/kibana-oss:6.4.2"
    #    #image: "blacktop/kibana"
    #    network_mode: "host"
    #    #command: [ "/bin/bash", "-c", "/usr/share/kibana/bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker" ]
    #    environment:
    #        - ELASTICSEARCH_URL="http://127.0.0.1:9200/"
    #        #- XPACK_ML_ENABLED=false
    #        #- XPACK_GRAPH_ENABLED=false
    #        #- XPACK_MONITORING_ENABLED=false
    #        #- XPACK_REPORTING_ENABLED=false
    #        #- XPACK_SECURITY_ENABLED=false

