version: "2.1" # https://docs.docker.com/compose/compose-file/#version-21
volumes:
    data-magento2.1-src:
        labels:
            com.example.b2b.description: "Magento 2.1 source code"
            com.example.b2b.department: "DevOps"
    data-db:
        labels:
            com.example.web1.description: "MySQL database"
            com.example.web1.department: "DevOps"
networks:
    front:
        #driver: "bridge"
        #ipam:
        #    config:
        #        - subnet: "172.25.0.0/24"
    back:
services:
    db1:
        #hostname: "db1.local"
        image: "mysql:5.7"
        volumes:
            - "data-db:/var/lib/mysql"
        networks:
            - "back"
        environment:
            MYSQL_ROOT_PASSWORD: "foo"
    app1:
        #hostname: "php1.local"
        image: "php:7.0-fpm"
        volumes:
            - "data-magento2.1-src:/var/www/html/magento2.1"
        networks:
            - "front"
            - "back"
            ##front:
            ##    aliases:
            ##        - "myappip"
            ##back:
        #expose:
        #    - "9000"
    web1:
        #hostname: "web1.local"
        image: "httpd:2.4"
        volumes:
            - "data-magento2.1-src:/usr/local/apache2/htdocs/magento2.1"
        networks:
            - "front"
        ports:
            - "80:80"
        #expose:
        #    - "80"
